<?php

// Exit if accessed directly
if ( !defined('ABSPATH')) exit;

/**
 *
 * WARNING: Please do not edit this file in any way
 *
 * load the theme function files
 */
require_once(TEMPLATEPATH . '/includes/functions/sidebars.php');
include(TEMPLATEPATH . '/includes/widgets.php');
require_once(TEMPLATEPATH . '/m_toolbox/m_toolbox.php');
require ( get_template_directory() . '/includes/functions.php' );
require ( get_template_directory() . '/includes/theme-options.php' );
require ( get_template_directory() . '/includes/hooks.php' );
require ( get_template_directory() . '/includes/version.php' );


